* ergoxkb
   
   xkb-ergo - дополнительная раскладка для Х'ов, подключаемая поверх языковой
   раскладки и переносящая управление курсором в home-row.
   
   Основное приимущество используемого подохода, биндинги на уровне системы /
   xkb, в том, что они работают в большинстве приложений без дополнительной
   настройки последних.

   Расположение клавиш вдохновленo модулем ergo для emacs, разработанным Xah
   Leе. Но в отлиичии от данного модуля, ориентированного исключительно на
   emacs, миссия данного проекта - экстраполяция биндингов на всю систему, все
   приложения.

** Что даёт данный лайаут

   - курсор и базовое редактирование в home-row
   - часто используемые символы ближе к home-row 
   - удобное расположение модификаторов caps/tab/spacebar
   - работа биндингов в большенстве приложений использующих xkb
   - управление курсором мыши с клавиатуры

** Источники

   - [[https://ergoemacs.github.io/][Xah Lee]]
   - [[http://pascal.tsu.ru/other/xkb/][Иван Паскаль]]
   - [[https://habrahabr.ru/post/222285/][Фил Пирожков]]
